- hosts: nodes
  become: true

  tasks:

#Downloading mySQL image
    - name: Download mySQL image
      command: docker pull mysql:5.7.42-debian

  #Downloading Task Manager App 
    - name: Download app image
      command: docker pull iaziogas/app:latest
  
  #Creating subnetwork on docker
    - name: Create a network
      command: docker network create -d bridge network_team_1

  #Creating a container for the database
    - name: Create the database
      command: docker run -d --network=network_team_1 -e MYSQL_ROOT_PASSWORD=root --name mySQL_DB mysql:5.7.42-debian
    
  #Obtaining the ip adress of the database
    -name: Obtaining ip adress
     ip_adress: command: docker container inspect -f "{{ .NetworkSettings.Networks.network_team_1.IPAddress }}" mySQL_DB

  #Creating a container for the app
    - name: Start the app 
      command: docker run -d -e DB_HOST={{ ip_adress }} --network=network_team_1 - -p 8080:8080 --name team_1_app iaziogas/app:latest